---
title: "Routine for TerraClim data extraction"
subtitle: "LSHTM - PHID"
Project: 
author:
- name: Gabriel Carrasco Escobar
  affiliation: UC San Diego / LSHTM (visitor)
Comment:
  web: 
  date: May 08, 2019
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: false
    toc_depth: 3
---
  
*Inquiries regarding this code contact gabriel.carrasco@lshtm.ac.uk*

# LOADING PACKAGES
```{r message = FALSE, warning = FALSE}
rm(list=ls())
library(tidyverse); library(maptools); library(epiDisplay)
library(gpclib); library(mapproj); library(climateR)
#devtools::install_github("mikejohnson51/climateR")
```

# ADMINISTRATIVE DATA (Shapefile)
```{r message = FALSE, warning = FALSE}
library(GADMTools)
LOR <- gadm_sp_loadCountries("PER", level=3, basefile="./") %>%
  gadm_subset(level = 1, regions="Loreto")
LOR<-LOR$spdf
```

# LORETO
```{r message = FALSE, warning = FALSE}
gpclibPermit()
map = fortify(LOR, region="NAME_3")
map %>% 
  ggplot(aes(x = long, y = lat, group = group)) +
  geom_polygon(color = "black", fill="white", size = 0.25) + 
  coord_map() +
  theme_bw()
```

# TerraClim data
```{r message = FALSE, warning = FALSE}  
AOI = getAOI(clip = LOR)
p = AOI %>% getTerraClim(param = c('tmax','tmin'), startDate = "2017-10-28")
r = raster::stack(p$tmax, p$tmin)
names(r) = c('tmax', 'tmin')
rasterVis::levelplot(r)

e = AOI %>% getTerraClim(param = c('q','prcp'), startDate = "2017-10-28")
r2 = raster::stack(e$q, e$prcp)
names(r2) = c('Runoff', 'prcp')
rasterVis::levelplot(r2)

g = AOI %>%  getTerraClim(param = 'tmax', startDate = "2017-10-28")
raster::plot(g$tmax, col = viridis::viridis(25), axes = F, box= F)
sp::plot(LOR, add = T)
```

